// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: online_shopping.proto

#include "online_shopping.pb.h"
#include "online_shopping.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace shopping {

static const char* OnlineShopping_method_names[] = {
  "/shopping.OnlineShopping/GetItems",
};

std::unique_ptr< OnlineShopping::Stub> OnlineShopping::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OnlineShopping::Stub> stub(new OnlineShopping::Stub(channel, options));
  return stub;
}

OnlineShopping::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetItems_(OnlineShopping_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OnlineShopping::Stub::GetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::shopping::GetItemsReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::shopping::GetItemsRequest, ::shopping::GetItemsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetItems_, context, request, response);
}

void OnlineShopping::Stub::async::GetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest* request, ::shopping::GetItemsReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::shopping::GetItemsRequest, ::shopping::GetItemsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetItems_, context, request, response, std::move(f));
}

void OnlineShopping::Stub::async::GetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest* request, ::shopping::GetItemsReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetItems_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::shopping::GetItemsReply>* OnlineShopping::Stub::PrepareAsyncGetItemsRaw(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::shopping::GetItemsReply, ::shopping::GetItemsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetItems_, context, request);
}

::grpc::ClientAsyncResponseReader< ::shopping::GetItemsReply>* OnlineShopping::Stub::AsyncGetItemsRaw(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetItemsRaw(context, request, cq);
  result->StartCall();
  return result;
}

OnlineShopping::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OnlineShopping_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OnlineShopping::Service, ::shopping::GetItemsRequest, ::shopping::GetItemsReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OnlineShopping::Service* service,
             ::grpc::ServerContext* ctx,
             const ::shopping::GetItemsRequest* req,
             ::shopping::GetItemsReply* resp) {
               return service->GetItems(ctx, req, resp);
             }, this)));
}

OnlineShopping::Service::~Service() {
}

::grpc::Status OnlineShopping::Service::GetItems(::grpc::ServerContext* context, const ::shopping::GetItemsRequest* request, ::shopping::GetItemsReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace shopping

