// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: online_shopping.proto
#ifndef GRPC_online_5fshopping_2eproto__INCLUDED
#define GRPC_online_5fshopping_2eproto__INCLUDED

#include "online_shopping.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace shopping {

class OnlineShopping final {
 public:
  static constexpr char const* service_full_name() {
    return "shopping.OnlineShopping";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::shopping::GetItemsReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shopping::GetItemsReply>> AsyncGetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shopping::GetItemsReply>>(AsyncGetItemsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shopping::GetItemsReply>> PrepareAsyncGetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::shopping::GetItemsReply>>(PrepareAsyncGetItemsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest* request, ::shopping::GetItemsReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest* request, ::shopping::GetItemsReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::shopping::GetItemsReply>* AsyncGetItemsRaw(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::shopping::GetItemsReply>* PrepareAsyncGetItemsRaw(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::shopping::GetItemsReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shopping::GetItemsReply>> AsyncGetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shopping::GetItemsReply>>(AsyncGetItemsRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shopping::GetItemsReply>> PrepareAsyncGetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::shopping::GetItemsReply>>(PrepareAsyncGetItemsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest* request, ::shopping::GetItemsReply* response, std::function<void(::grpc::Status)>) override;
      void GetItems(::grpc::ClientContext* context, const ::shopping::GetItemsRequest* request, ::shopping::GetItemsReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::shopping::GetItemsReply>* AsyncGetItemsRaw(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::shopping::GetItemsReply>* PrepareAsyncGetItemsRaw(::grpc::ClientContext* context, const ::shopping::GetItemsRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetItems_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetItems(::grpc::ServerContext* context, const ::shopping::GetItemsRequest* request, ::shopping::GetItemsReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetItems() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetItems(::grpc::ServerContext* /*context*/, const ::shopping::GetItemsRequest* /*request*/, ::shopping::GetItemsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetItems(::grpc::ServerContext* context, ::shopping::GetItemsRequest* request, ::grpc::ServerAsyncResponseWriter< ::shopping::GetItemsReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetItems<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetItems() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::shopping::GetItemsRequest, ::shopping::GetItemsReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::shopping::GetItemsRequest* request, ::shopping::GetItemsReply* response) { return this->GetItems(context, request, response); }));}
    void SetMessageAllocatorFor_GetItems(
        ::grpc::MessageAllocator< ::shopping::GetItemsRequest, ::shopping::GetItemsReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::shopping::GetItemsRequest, ::shopping::GetItemsReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetItems(::grpc::ServerContext* /*context*/, const ::shopping::GetItemsRequest* /*request*/, ::shopping::GetItemsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetItems(
      ::grpc::CallbackServerContext* /*context*/, const ::shopping::GetItemsRequest* /*request*/, ::shopping::GetItemsReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetItems<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetItems() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetItems(::grpc::ServerContext* /*context*/, const ::shopping::GetItemsRequest* /*request*/, ::shopping::GetItemsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetItems() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetItems(::grpc::ServerContext* /*context*/, const ::shopping::GetItemsRequest* /*request*/, ::shopping::GetItemsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetItems(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetItems() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetItems(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetItems(::grpc::ServerContext* /*context*/, const ::shopping::GetItemsRequest* /*request*/, ::shopping::GetItemsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetItems(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetItems : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetItems() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::shopping::GetItemsRequest, ::shopping::GetItemsReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::shopping::GetItemsRequest, ::shopping::GetItemsReply>* streamer) {
                       return this->StreamedGetItems(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetItems() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetItems(::grpc::ServerContext* /*context*/, const ::shopping::GetItemsRequest* /*request*/, ::shopping::GetItemsReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetItems(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::shopping::GetItemsRequest,::shopping::GetItemsReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetItems<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetItems<Service > StreamedService;
};

}  // namespace shopping


#endif  // GRPC_online_5fshopping_2eproto__INCLUDED
